openapi: 3.0.1
info:
  title: Catchpoint REST API v2.0 Account UsageReport API
  version: '2.0'
servers:
- url: /api
tags:
- name: UsageReport
paths:
  /v2/account/usagereport:
    get:
      tags:
      - UsageReport
      summary: Returns the Usage Report
      description: " Return usage report for the provided parameters.  \r\nThe parameters are optional, and you may include either of them to customize the query.If no parameters are passed, then usage report by months is returned."
      parameters:
      - name: dataByDays
        in: query
        description: Usage Report of last 7 days including the present day.
        schema:
          type: boolean
      - name: dataByWeeks
        in: query
        description: Usage Report of last 5 weeks including present week.
        schema:
          type: boolean
      - name: dataByMonths
        in: query
        description: Usage Report of last 4 Months including the current month.
        schema:
          type: boolean
      - name: dataByQuarters
        in: query
        description: Usage Report of last 3 quarters including current quarter.
        schema:
          type: boolean
      - name: divisionId
        in: query
        description: Division id of which usage report Required
        schema:
          type: integer
          format: int32
      - name: productId
        in: query
        description: ProductId if which usage report required
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Response.APIResponse`1[Catchpoint.Symphony.REST.Common.Response.v2_0.UsageReportResponseModel]'
            text/plain:
              schema:
                $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Response.APIResponse`1[Catchpoint.Symphony.REST.Common.Response.v2_0.UsageReportResponseModel]'
            text/json:
              schema:
                $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Response.APIResponse`1[Catchpoint.Symphony.REST.Common.Response.v2_0.UsageReportResponseModel]'
      security:
      - bearer: []
      order: 1
components:
  schemas:
    ? Catchpoint.Symphony.REST.Common.Response.APIResponse`1[Catchpoint.Symphony.REST.Common.Response.v2_0.UsageReportResponseModel]
    : type: object
      properties:
        data:
          $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Response.v2_0.UsageReportResponseModel'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.InfoMessage'
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.ViewModels.MessageModel'
          nullable: true
        completed:
          type: boolean
          readOnly: true
        traceId:
          type: string
          nullable: true
        usageLimits:
          $ref: '#/components/schemas/Catchpoint.Symphony.REST.Api.ApiUsageStatistics'
      additionalProperties: false
    Catchpoint.Symphony.REST.Api.ApiUsageStatistics:
      type: object
      properties:
        clientId:
          type: integer
          format: int64
        lastRequestTimestamp:
          type: string
          format: date-time
        limits:
          $ref: '#/components/schemas/Catchpoint.Symphony.REST.Api.Limit'
        runs:
          $ref: '#/components/schemas/Catchpoint.Symphony.REST.Api.Limit'
        exceededMessage:
          type: string
          nullable: true
          readOnly: true
        divisionUsageStatistics:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Api.DivisionUsageStatistics'
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsDataAPIModel:
      type: object
      properties:
        divisionData:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsUsageDataAPIModel'
          nullable: true
        productData:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsUsageDataAPIModel'
          nullable: true
        sumTotalPoints:
          type: number
          format: double
          nullable: true
        allowanceTotalPoints:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsUsageDataAPIModel:
      type: object
      properties:
        divisionId:
          type: integer
          format: int32
          nullable: true
        divisionName:
          type: string
          nullable: true
        productId:
          type: integer
          format: int32
          nullable: true
        productName:
          type: string
          nullable: true
        points:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.DoubleDateTimeDataPointAPIModel'
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.TotalPointAPIModel:
      type: object
      properties:
        divisionId:
          type: integer
          format: int64
          nullable: true
        productId:
          type: integer
          format: int64
          nullable: true
        aggregatedTotal:
          type: number
          format: double
          nullable: true
        totalAllocatedPoints:
          type: number
          format: double
          nullable: true
        allowance:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Models.InfoMessage:
      type: object
      properties:
        information:
          type: string
          nullable: true
        ignoredPath:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.PatchIgnoredPath'
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.DoubleDateTimeDataPointAPIModel:
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
          nullable: true
        value:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Api.Limit:
      type: object
      properties:
        minute:
          type: integer
          format: int32
        hour:
          type: integer
          format: int32
        day:
          type: integer
          format: int32
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Response.v2_0.UsageReportResponseModel:
      type: object
      properties:
        day:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsDataAPIModel'
          nullable: true
        week:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsDataAPIModel'
          nullable: true
        month:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsDataAPIModel'
          nullable: true
        quarter:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.PointsDataAPIModel'
          nullable: true
        totalPoints:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Common.Models.v2_0.UsageReport.TotalPointAPIModel'
          nullable: true
        startDate:
          type: string
          format: date-time
          nullable: true
        endDate:
          type: string
          format: date-time
          nullable: true
        totalPointsUsed:
          type: number
          format: double
          nullable: true
        contractBalance:
          type: number
          format: double
          nullable: true
        hasMore:
          type: boolean
          nullable: true
        next:
          type: string
          nullable: true
        previous:
          type: string
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Api.ConsumerStatistics:
      type: object
      properties:
        consumerId:
          type: integer
          format: int32
        requestCount:
          $ref: '#/components/schemas/Catchpoint.Symphony.REST.Api.Limit'
        maxPerDay:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Common.Models.PatchIgnoredPath:
      type: object
      properties:
        ops:
          type: string
          nullable: true
        path:
          type: string
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.ViewModels.MessageModel:
      type: object
      properties:
        id:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    Catchpoint.Symphony.REST.Api.DivisionUsageStatistics:
      type: object
      properties:
        divisionId:
          type: integer
          format: int32
        consumerStatistics:
          type: array
          items:
            $ref: '#/components/schemas/Catchpoint.Symphony.REST.Api.ConsumerStatistics'
          nullable: true
      additionalProperties: false
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
